import type { RecurringType } from '@/shared/types';

/**
 * Which semantic category a recurring kind implies, so picking the kind is
 * also the category choice — no second step in the form.
 *
 * The targets are ordinary preset categories, NOT a «Recurring» bucket: rent
 * belongs next to the rest of Home in analytics whether it was entered by hand
 * or generated by a template ("context is not category"). The recurring view
 * of the same spend comes from the `recurring` tag, which every generated
 * expense already carries.
 *
 * `custom` maps to nothing on purpose — a user-labelled kind carries no
 * semantics we could guess, so that one still asks.
 */
export interface ImpliedCategory {
  /** Preset category id (stable, doubles as the Firestore doc id) */
  categoryId: string;
  /** Preset folder the category lives in, needed when materializing it */
  folderId: string;
}

export const RECURRING_TYPE_CATEGORY: Record<RecurringType, ImpliedCategory | null> = {
  subscription: { categoryId: 'sub_generic', folderId: 'subscriptions' },
  rent: { categoryId: 'rent', folderId: 'home' },
  utility: { categoryId: 'utilities', folderId: 'home' },
  credit: { categoryId: 'credit_payment', folderId: 'finance' },
  mortgage: { categoryId: 'mortgage', folderId: 'home' },
  installment: { categoryId: 'installment_pay', folderId: 'finance' },
  custom: null,
};

export function impliedCategoryFor(type: RecurringType): ImpliedCategory | null {
  return RECURRING_TYPE_CATEGORY[type] ?? null;
}
