/**
 * Subscription auto-detect: same merchant, near-equal amount, ~monthly
 * cadence. Suggestion signal only — never auto-creates anything.
 */
import { describe, it, expect } from 'vitest';
import { detectSubscriptionCandidates } from '@/features/recurring/utils/subscriptionDetect';
import type { Currency } from '@/shared/types';

const NOW = new Date('2026-07-16T12:00:00');

const exp = (date: string, amount: number, over: Record<string, unknown> = {}) => ({
  amount,
  currency: 'ILS' as Currency,
  categoryId: 'subscriptions',
  date: `${date}T10:00:00.000Z`,
  store: 'Netflix',
  storeId: 'netflix',
  isRecurring: false,
  tags: [] as string[],
  splits: [],
  ...over,
});

const detect = (expenses: ReturnType<typeof exp>[], over: Record<string, unknown> = {}) =>
  detectSubscriptionCandidates({ expenses, templates: [], now: NOW, ...over });

describe('detectSubscriptionCandidates', () => {
  it('detects three near-equal monthly charges from one merchant', () => {
    const out = detect([exp('2026-05-05', 45), exp('2026-06-05', 45), exp('2026-07-05', 47)]);
    expect(out).toHaveLength(1);
    expect(out[0]).toMatchObject({
      key: 'netflix::ILS',
      displayName: 'Netflix',
      amount: 47, // latest price wins
      occurrences: 3,
    });
    // Suggested start is strictly in the future — next expected charge
    expect(new Date(out[0].suggestedStartDate) > NOW).toBe(true);
  });

  it('needs at least three charges', () => {
    expect(detect([exp('2026-06-05', 45), exp('2026-07-05', 45)])).toHaveLength(0);
  });

  it('rejects non-monthly cadence (weekly groceries)', () => {
    const out = detect([exp('2026-07-01', 45), exp('2026-07-08', 45), exp('2026-07-15', 45)]);
    expect(out).toHaveLength(0);
  });

  it('rejects amount drift beyond ±15%', () => {
    const out = detect([exp('2026-05-05', 40), exp('2026-06-05', 40), exp('2026-07-05', 60)]);
    expect(out).toHaveLength(0);
  });

  it('ignores charges generated by existing templates', () => {
    const out = detect([
      exp('2026-05-05', 45, { recurringId: 'r1' }),
      exp('2026-06-05', 45, { recurringId: 'r1' }),
      exp('2026-07-05', 45, { recurringId: 'r1' }),
    ]);
    expect(out).toHaveLength(0);
  });

  it('skips merchants already covered by a template with the same name', () => {
    const charges = [exp('2026-05-05', 45), exp('2026-06-05', 45), exp('2026-07-05', 45)];
    expect(detect(charges, { templates: [{ name: 'Netflix' }] })).toHaveLength(0);
  });

  it('respects the dismissed list', () => {
    const charges = [exp('2026-05-05', 45), exp('2026-06-05', 45), exp('2026-07-05', 45)];
    expect(detect(charges, { dismissedKeys: ['netflix::ILS'] })).toHaveLength(0);
  });

  it('drops merchants whose last charge is stale (> 40 days)', () => {
    const out = detect([exp('2026-03-20', 45), exp('2026-04-20', 45), exp('2026-05-20', 45)]);
    expect(out).toHaveLength(0);
  });

  it('collapses same-day duplicates before gap math', () => {
    const out = detect([
      exp('2026-05-05', 45), exp('2026-05-05', 45),
      exp('2026-06-05', 45), exp('2026-07-05', 45),
    ]);
    expect(out).toHaveLength(1);
    expect(out[0].occurrences).toBe(3);
  });

  it('rolls the suggested start past today, keeping the billing day', () => {
    const out = detect([exp('2026-04-10', 45), exp('2026-05-10', 45), exp('2026-06-10', 45)]);
    expect(out).toHaveLength(1);
    const d = new Date(out[0].suggestedStartDate);
    expect(d > NOW).toBe(true);
    expect(d.getDate()).toBe(10);
  });
});
