import { buildStatsDelta, buildMonthlyStatsPatch, type StatsDelta } from '../utils/expenseStats';
export { statsPatchShape, type StatsDelta } from '../utils/expenseStats';
import {
  collection,
  doc,
  getDoc,
  getDocs,
  query,
  orderBy,
  limit,
  startAfter,
  where,
  writeBatch,
  runTransaction,
  deleteField,
  increment,
  serverTimestamp,
  Timestamp,
  type DocumentSnapshot,
  type Transaction,
  type WriteBatch,
} from 'firebase/firestore';
import { format } from 'date-fns';
import { getDb } from '@/shared/lib/firebase';
import { toLocalMonthKey } from '@/shared/utils/dateKey';
import { prepareExpenseLinks, type ExpenseLinksUndo } from './expenseLinks';
import { readEntryPrivacy } from '@/shared/services/entryPrivacy';
import type {
  Currency,
  Expense,
  ExpenseItem,
  PaymentMethod,
  Privacy,
  SerializableExpense,
  SplitItem,
} from '@/shared/types';

const PAGE_SIZE = 20;
const MONEY_EPSILON = 0.01;

function expCol(userId: string) {
  return collection(getDb(), 'expenses', userId, 'items');
}

function expenseDoc(userId: string, expenseId?: string) {
  return expenseId
    ? doc(getDb(), 'expenses', userId, 'items', expenseId)
    : doc(expCol(userId));
}

function statsDoc(userId: string, month: string) {
  return doc(getDb(), 'monthlyStats', userId, 'months', month);
}

function toSerializable(id: string, data: Record<string, unknown>): SerializableExpense {
  const toISO = (value: unknown) =>
    value instanceof Timestamp ? value.toDate().toISOString() : (value as string) ?? new Date().toISOString();

  return {
    id,
    userId: data.userId as string,
    amount: data.amount as number,
    currency: data.currency as Currency,
    categoryId: data.categoryId as string,
    date: toISO(data.date),
    paymentMethod: data.paymentMethod as PaymentMethod,
    store: data.store as string | undefined,
    storeId: data.storeId as string | undefined,
    storeGroup: data.storeGroup as string | undefined,
    tags: (data.tags as string[]) ?? [],
    comment: data.comment as string | undefined,
    photoUrl: data.photoUrl as string | undefined,
    privacy: data.privacy as Privacy,
    splits: (data.splits as SplitItem[]) ?? [],
    items: (data.items as ExpenseItem[] | undefined) ?? undefined,
    isRecurring: (data.isRecurring as boolean) ?? false,
    recurringId: data.recurringId as string | undefined,
    goalId: data.goalId as string | undefined,
    goalOwnerId: data.goalOwnerId as string | undefined,
    contributionId: data.contributionId as string | undefined,
    reactions: data.reactions as Record<string, string> | undefined,
    createdAt: toISO(data.createdAt),
    updatedAt: toISO(data.updatedAt),
  };
}

export async function fetchMonthExpenses(userId: string, month: string): Promise<SerializableExpense[]> {
  const [year, m] = month.split('-').map(Number);
  const from = Timestamp.fromDate(new Date(year, m - 1, 1));
  const to = Timestamp.fromDate(new Date(year, m, 1));

  const snap = await getDocs(
    query(expCol(userId), where('date', '>=', from), where('date', '<', to), orderBy('date', 'desc')),
  );
  return snap.docs.map((d) => toSerializable(d.id, d.data()));
}

/**
 * Month expenses as visible to OTHER family members: only privacy ==
 * 'regular'. The equality filter is mandatory — security rules prove
 * family list queries against it, a query without it is denied.
 */
export async function fetchSharedMonthExpenses(userId: string, month: string): Promise<SerializableExpense[]> {
  const [year, m] = month.split('-').map(Number);
  const from = Timestamp.fromDate(new Date(year, m - 1, 1));
  const to = Timestamp.fromDate(new Date(year, m, 1));

  const snap = await getDocs(
    query(
      expCol(userId),
      where('privacy', '==', 'regular'),
      where('date', '>=', from), where('date', '<', to),
      orderBy('date', 'desc'),
    ),
  );
  return snap.docs.map((d) => toSerializable(d.id, d.data()));
}

/**
 * Every expense generated by one recurring template, newest first.
 *
 * Deliberately a single equality filter with no `orderBy`: `where` + `orderBy`
 * on different fields would need a composite index deployed, and a payment
 * history is a handful of documents — sorting here costs nothing.
 */
export async function fetchExpensesByRecurringId(
  userId: string,
  recurringId: string,
): Promise<SerializableExpense[]> {
  const snap = await getDocs(query(expCol(userId), where('recurringId', '==', recurringId)));
  return snap.docs
    .map((d) => toSerializable(d.id, d.data()))
    .sort((a, b) => b.date.localeCompare(a.date));
}

/** Shared (privacy == 'regular') expenses over an arbitrary date range — one query per member for family analytics. */
export async function fetchSharedExpensesInRange(userId: string, from: Date, to: Date): Promise<SerializableExpense[]> {
  const snap = await getDocs(
    query(
      expCol(userId),
      where('privacy', '==', 'regular'),
      where('date', '>=', Timestamp.fromDate(from)), where('date', '<', Timestamp.fromDate(to)),
      orderBy('date', 'desc'),
    ),
  );
  return snap.docs.map((d) => toSerializable(d.id, d.data()));
}

export interface AddExpenseInput {
  userId: string;
  amount: number;
  currency: Currency;
  categoryId: string;
  date: Date;
  paymentMethod: PaymentMethod;
  store?: string;
  storeId?: string;
  storeGroup?: string;
  tags: string[];
  comment?: string;
  privacy: Privacy;
  splits: SplitItem[];
  items?: ExpenseItem[];
  goalId?: string;
  /** Owner of the linked goal (contributions to another member's goal) */
  goalOwnerId?: string;
  /** Id of the linked contribution — exact rollback key on delete */
  contributionId?: string;
  recurringId?: string;
  isRecurring?: boolean;
  /** Stable retry key for the originating chat message or form submission. */
  operationId?: string;
}

/**
 * Queues the expense document plus its monthlyStats delta into the caller's
 * batch without committing. Lets multi-entity flows (e.g. savings
 * contribution + expense) stay atomic in a single WriteBatch.
 */
export function queueAddExpense(batch: WriteBatch | Transaction, input: AddExpenseInput, expenseId?: string): SerializableExpense {
  validateExpenseInput(input);
  const { userId, date, store, storeId, storeGroup, comment, operationId: _operationId, ...rest } = input;
  const ref = expenseDoc(userId, expenseId);
  const data = Object.fromEntries(
    Object.entries({
      ...rest,
      userId,
      store,
      storeId,
      storeGroup,
      comment,
      date: Timestamp.fromDate(date),
      isRecurring: input.isRecurring ?? Boolean(input.recurringId),
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    }).filter(([, value]) => value !== undefined),
  );

  // WriteBatch.set and Transaction.set differ only in return type — TS cannot
  // call the union directly, the runtime shape is identical.
  (batch as WriteBatch).set(ref, data);
  queueMonthlyStatsUpdate(
    batch,
    userId,
    format(date, 'yyyy-MM'),
    buildStatsDelta(input.categoryId, input.amount, input.splits, 1, input.currency),
  );

  return toSerializable(ref.id, {
    ...data,
    date: Timestamp.fromDate(date),
    createdAt: Timestamp.fromDate(new Date()),
    updatedAt: Timestamp.fromDate(new Date()),
  });
}

export async function addExpense(input: AddExpenseInput): Promise<SerializableExpense> {
  const ref = expenseDoc(input.userId);
  const receipt = input.operationId ? doc(getDb(), 'users', input.userId, 'entryOperations', input.operationId) : null;
  return runTransaction(getDb(), async tx => {
    if (receipt) {
      const prior = await tx.get(receipt);
      if (prior.exists()) {
        if (prior.data().kind !== 'expense') throw new Error('operation-conflict');
        const saved = await tx.get(expenseDoc(input.userId, prior.data().entryId));
        if (!saved.exists()) throw new Error('entry-already-deleted');
        return toSerializable(saved.id, saved.data());
      }
    }
    const privacy = await readEntryPrivacy(tx, input.userId, 'expense', [input.categoryId, ...input.splits.map(s => s.categoryId)], input.privacy);
    const expense = queueAddExpense(tx, { ...input, privacy }, ref.id);
    if (receipt) tx.set(receipt, { kind: 'expense', entryId: ref.id, createdAt: serverTimestamp() });
    return expense;
  });
}

export interface UpdateExpenseInput extends AddExpenseInput {
  id: string;
  previousExpense?: SerializableExpense;
}

export async function updateExpense(input: UpdateExpenseInput): Promise<SerializableExpense> {
  validateExpenseInput(input);
  const { userId, id, previousExpense: _previous, operationId: _operation, goalId: _goalId, goalOwnerId: _goalOwnerId, contributionId: _contributionId, recurringId: _recurringId, isRecurring: _isRecurring, date, ...changes } = input;
  return runTransaction(getDb(), async tx => {
    const ref = expenseDoc(userId, id);
    const snap = await tx.get(ref);
    if (!snap.exists()) throw new Error('expense-not-found');
    const existing = toSerializable(id, snap.data());
    // Linked entries have their own lifecycle. Preserve their identity and do
    // not let the generic editor change the linked money/date/currency.
    if ((existing.goalId || existing.recurringId) && (existing.amount !== input.amount
      || existing.currency !== input.currency || toLocalMonthKey(existing.date) !== toLocalMonthKey(date)
      || new Date(existing.date).toDateString() !== date.toDateString())) {
      throw new Error('linked-expense-use-original-flow');
    }
    const privacy = await readEntryPrivacy(tx, userId, 'expense', [input.categoryId, ...input.splits.map(s => s.categoryId)],
      existing.privacy === 'secret' ? 'secret' : input.privacy, true);
    const data = Object.fromEntries(Object.entries({ ...changes, userId, privacy,
      date: Timestamp.fromDate(date), isRecurring: existing.isRecurring,
      comment: input.comment ?? deleteField(), updatedAt: serverTimestamp(),
    }).filter(([, value]) => value !== undefined));
    tx.update(ref, data);
    const statsByMonth = new Map<string, { month: string; delta: StatsDelta }>();
    mergeStatsDelta(statsByMonth, toLocalMonthKey(existing.date), buildStatsDelta(existing.categoryId, existing.amount, existing.splits, -1, existing.currency));
    mergeStatsDelta(statsByMonth, toLocalMonthKey(date), buildStatsDelta(input.categoryId, input.amount, input.splits, 1, input.currency));
    for (const { month, delta } of statsByMonth.values()) queueMonthlyStatsUpdate(tx, userId, month, delta);
    return { ...existing, ...changes, userId, id, privacy, isRecurring: existing.isRecurring,
      date: date.toISOString(), comment: input.comment, updatedAt: new Date().toISOString() };
  });
}

function validateExpenseInput(input: AddExpenseInput) {
  if (!Number.isFinite(input.amount) || input.amount <= 0) {
    throw new Error('Expense amount must be greater than zero');
  }

  if (!input.categoryId || input.categoryId.trim().length === 0) {
    throw new Error('Expense categoryId is required');
  }

  if (!(input.date instanceof Date) || Number.isNaN(input.date.getTime())) {
    throw new Error('Expense date is invalid');
  }

  const splitTotal = input.splits.reduce((total, split) => {
    if (!split.categoryId || split.categoryId.trim().length === 0) {
      throw new Error('Split categoryId is required');
    }
    if (!Number.isFinite(split.amount) || split.amount < 0) {
      throw new Error('Split amount must be zero or greater');
    }
    return total + split.amount;
  }, 0);

  if (splitTotal > input.amount + MONEY_EPSILON) {
    throw new Error('Split total cannot exceed expense amount');
  }
}

export interface ExpenseDeletion {
  expense: SerializableExpense | null;
  links: ExpenseLinksUndo;
  recurring: import('@/shared/types').SerializableRecurringPayment | null;
}

export async function deleteExpense(userId: string, expense: SerializableExpense): Promise<ExpenseDeletion> {
  const messages = await getDocs(query(collection(getDb(), 'messages', userId, 'items'), where('expenseId', '==', expense.id)));
  const run = (skipGoal: boolean) => runTransaction(getDb(), async tx => {
    const ref = expenseDoc(userId, expense.id);
    const snap = await tx.get(ref);
    if (!snap.exists()) return { expense: null, links: {}, recurring: null };
    const current = toSerializable(snap.id, snap.data());
    const links = await prepareExpenseLinks(tx, userId, current, undefined, { skipGoal });
    links.apply();
    tx.delete(ref);
    messages.docs.forEach(d => tx.delete(d.ref));
    queueMonthlyStatsUpdate(tx, userId, toLocalMonthKey(current.date), buildStatsDelta(current.categoryId, current.amount, current.splits, -1, current.currency));
    return { expense: current, links: links.undo, recurring: links.recurring };
  });
  try {
    return await run(false);
  } catch (error) {
    // Another member's goal can stop being readable or writable for us: made
    // private, deleted, or we left the family. Its contribution cannot be
    // rolled back then, but our own expense must still be deletable.
    const foreignGoal = !!expense.goalId && (expense.goalOwnerId ?? userId) !== userId;
    if (!foreignGoal || (error as { code?: string }).code !== 'permission-denied') throw error;
    return run(true);
  }
}

/** Undo uses the actual deleted snapshot, and commits linked state with the money. */
export async function restoreExpense(userId: string, deletion: ExpenseDeletion) {
  const expense = deletion.expense;
  if (!expense) return null;
  return runTransaction(getDb(), async tx => {
    const ref = expenseDoc(userId, expense.id);
    if ((await tx.get(ref)).exists()) return null;
    const links = await prepareExpenseLinks(tx, userId, expense, deletion.links);
    const privacy = await readEntryPrivacy(tx, userId, 'expense', [expense.categoryId, ...expense.splits.map(s => s.categoryId)], expense.privacy, true);
    links.apply();
    const { id: _id, ...fields } = expense;
    const data = Object.fromEntries(Object.entries({ ...fields, userId, privacy,
      date: Timestamp.fromDate(new Date(expense.date)), createdAt: isoToTimestamp(expense.createdAt), updatedAt: serverTimestamp(),
    }).filter(([,v]) => v !== undefined));
    tx.set(ref, data);
    queueMonthlyStatsUpdate(tx, userId, toLocalMonthKey(expense.date), buildStatsDelta(expense.categoryId, expense.amount, expense.splits, 1, expense.currency));
    return links.recurring;
  });
}

/**
 * Find chat messages that reference this entity (by top-level expenseId/incomeId field)
 * and queue them for deletion in the same batch. Idempotent — no-ops when no message
 * was ever linked. Shared with incomeService/recurring/savings via a thin wrapper.
 */
export async function queueLinkedChatMessageDeletes(
  batch: WriteBatch,
  userId: string,
  field: 'expenseId' | 'incomeId',
  entityId: string,
): Promise<void> {
  const msgCol = collection(getDb(), 'messages', userId, 'items');
  const snap = await getDocs(query(msgCol, where(field, '==', entityId)));
  snap.docs.forEach((d) => batch.delete(d.ref));
}

/**
 * Deltas are merged per month AND per currency: an edit may move an expense
 * between currencies, and folding those into one delta would corrupt the
 * per-currency totals.
 */
function statsBucketKey(month: string, currency: Currency): string {
  return `${month}|${currency}`;
}

function mergeStatsDelta(
  target: Map<string, { month: string; delta: StatsDelta }>,
  month: string,
  incoming: StatsDelta,
) {
  const key = statsBucketKey(month, incoming.currency);
  const bucket = target.get(key);
  if (!bucket) {
    target.set(key, {
      month,
      delta: {
        currency: incoming.currency,
        totalExpenses: incoming.totalExpenses,
        byCategory: { ...incoming.byCategory },
      },
    });
    return;
  }

  bucket.delta.totalExpenses += incoming.totalExpenses;
  for (const [categoryId, delta] of Object.entries(incoming.byCategory)) {
    bucket.delta.byCategory[categoryId] = (bucket.delta.byCategory[categoryId] ?? 0) + delta;
  }
}

function queueMonthlyStatsUpdate(
  batch: WriteBatch | Transaction,
  userId: string,
  month: string,
  delta: StatsDelta,
) {
  const patch = buildMonthlyStatsPatch(userId, month, delta, increment, serverTimestamp());
  if (patch) (batch as WriteBatch).set(statsDoc(userId, month), patch, { merge: true });
}

export async function fetchExpenseById(userId: string, expenseId: string): Promise<SerializableExpense> {
  const snap = await getDoc(expenseDoc(userId, expenseId));
  if (!snap.exists()) {
    throw new Error('expense-not-found');
  }

  return toSerializable(snap.id, snap.data());
}

function isoToTimestamp(iso: string): Timestamp {
  return Timestamp.fromDate(new Date(iso));
}

/**
 * №9 migration: expenses whose category (or any split category) is private
 * but were saved before the private→secret rule must be flipped to secret,
 * or the family would still see their amounts. Owner-side, idempotent, runs
 * on the months the user loads. Only the `privacy` field changes — amounts
 * and monthlyStats are untouched. Returns the ids that were updated.
 */
export async function backfillPrivateCategoryExpenses(
  userId: string,
  expenses: SerializableExpense[],
  privateCategoryIds: Set<string>,
): Promise<string[]> {
  if (privateCategoryIds.size === 0) return [];
  const toFix = expenses.filter((e) =>
    e.privacy !== 'secret'
    && (privateCategoryIds.has(e.categoryId)
        || (e.splits ?? []).some((s) => privateCategoryIds.has(s.categoryId))),
  );
  if (toFix.length === 0) return [];
  const batch = writeBatch(getDb());
  for (const e of toFix) {
    batch.update(expenseDoc(userId, e.id), { privacy: 'secret', updatedAt: serverTimestamp() });
  }
  await batch.commit();
  return toFix.map((e) => e.id);
}

export type { Expense };
